// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

function evenFibSum() {

var fibSum = 2;
var currentFib = null;
var last = 2;
var beforeLast = 1;

while(currentFib < 4000000){
	currentFib = beforeLast + last;
	
	if(currentFib % 2 === 0){
		fibSum += currentFib;
	};

	beforeLast = last;
	last = currentFib;
}

return fibSum;

};

console.log(evenFibSum())